from typing import List, Mapping, Optional, Sequence

TEXT = str
OPTIONAL_TEXT = Optional[TEXT]
TEXT_SEQUENCE = Sequence[TEXT]
TEXT_TRANSLATION = Mapping[TEXT, TEXT]
# PHRASE_TRANSLATION = Mapping[TEXT, TEXT_TRANSLATION]
PHRASE_TRANSLATION = Mapping[TEXT, TEXT]
MULTIPLE_PHRASES_TRANSLATION = List[PHRASE_TRANSLATION]
